[package]
name = "approximate-cost-search"
version = "0.1.0"
edition = "2021"

[dependencies]
graphs = { git = "https://github.com/TiagoCavalcante/graphs", tag = "0.3.1" }
ordered-float = "3.0.0"
priority-queue = "1.2.3"
